# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies specified in the requirements file
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY src/ /app/src

# Set environment variables for MySQL (these can be overridden with `docker run -e`)
ENV MYSQL_HOST=mysql
ENV MYSQL_PORT=3306
ENV MYSQL_USER=your_username
ENV MYSQL_PASSWORD=your_password
ENV MYSQL_DATABASE=your_database
ENV PYTHONPATH=/app/src

# Expose port 3004 for the SSE server
EXPOSE 3004

# Command to run the SSE server
CMD ["uvicorn", "mysql_mcp_server.sse:api", "--host", "0.0.0.0", "--port", "3004"]